####################################################
#                                                  #
#                  Media Players                   #
#                                                  #
####################################################

- platform: soundtouch
  host: 172.16.10.15
  port: 8090
  name: Bose SoundTouch