####################################################
#                                                  #
#                        TTS                       #
#                                                  #
####################################################

####################################################
#                  Google Translate                #
####################################################

- platform: google_translate
  base_url: http://172.16.10.3:8123
  service_name: google_say